server:
  port: 18080
spring:
  application:
    name: sentinel-helloworld
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8081
        port: 8719
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
feign:
  sentinel:
    enabled: true